language: rust

os:
  - linux

cache: cargo

addons:
  apt:
    sources:
      - sourceline: 'ppa:wireguard/wireguard'
    packages:
      - linux-headers-$(uname -r)
      - wireguard

stages:
  - build
  - lint
  - test

jobs:
  allow_failures:
    - dist: focal

  include:

    - stage: build
      script:
        - cargo build --verbose

    - stage: lint
      name: Clippy
      script:
        - rustup component add clippy
        - cargo clippy --all-targets --all-features

    - stage: lint
      name: rustfmt
      script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check

    - stage: test
      script:
        - cargo build --tests --verbose
        # Give compiled tests the ability to set and read WireGuard devices. Otherwise
        # they will likely fail with access/permission errors.
        - find ./target/debug -maxdepth 1 -type f -executable | xargs -n 1 sudo setcap CAP_NET_ADMIN=+eip
        - cargo test --verbose
